mapbox/geocoder-abbreviations

- test.js
Test each global regex to ensure that an invalid regex causes failed tests.
Encountered this yesterday when migrating some new regexes into this repo that a newline when copying messed up the regex but still passed tests.
cc/ @yhahn
> Ensure regexes are valid

- tokens/en.json
Gettin' a release out with @apendleton's fix.
> Remove the "Bvd" abbreviation for boulevard

- tokens/fr.json
"Bis" is used in French addresses to indicate a sub-unit like a basement or semi-attached area, not unlike `221B Baker Street` in English.
This abbreviation is of relatively minor importance, and leads to a number of false positives. Removing will lead to better behavior on net.
> remove Bis:B abbreviation from fr token list

- tokens/de.json
This is kind of an odd PR, but it adds a couple of extra replacements for German to normalize umlauts that are represented in a new format being added to carmen to control whether or not token replacements have to be bounded by word boundaries (typically they do, but these don't).
> Add complex replacements for umlauts in german

- tokens/en.json
“Pky.” is a common abbreviation for “parkway” used throughout the United States and officially by the [USPS](http://pe.usps.gov/text/pub28/28apc_002.htm). “Py.” is much rarer; recently San José posted a sign bearing this abbreviation on [this traffic light](http://www.openstreetmap.org/node/245919607).
> Parkway as Py, Pky

- tokens/fr.json
I ran into these missing tokens while loading address data from Canadian sources.
> add boul, aut for boulevard, autoroute

- tokens/en.json
Too many false matches, these make it difficult to search by category.
> remove church, school, and station token replacers

- tokens/en.json
This PR leverages some recent work allowing for more expressive replacements to add a bunch of new token replacements targeted specifically at stripping unit numbers from addresses. For now, most of these changes are scoped to the US out of an abundance of caution.
Concretely, the PR adds support for stripping unit numbers of the formats:
* one of the designators `apartment`, `apt`, `bldg`, `building`, `rm`, `room`, and `unit` followed optionally by a pound sign followed by a unit number of any of the formats `[number]`, `[single letter]`, `[number][single letter]`, `[single letter][number]`, `[number]-[number]`, `[number]/[number]`, `[number]-[number][letter]`
* two special formats specifically for floor numbers: `[number][ordinal]` followed by `fl` or `floor`, and `fl` or `floor` …
> US unit number stripping

- src/lib.rs
As part of downstream work, makes several improvements to the Rust library to make structs more accessible (`pub`) and variants tightly defined (adding `enum`s).
I'll likely leave this PR open as work moves downstream in case I need to make any additional changes. One problem I'm consistently running into is the lack of traits implemented on external fancy-regex types, particularly `PartialEq` and `Debug`. Per [the docs](https://doc.rust-lang.org/book/ch10-02-traits.html), you can’t implement external traits on external types. I'll eventually need to implement one of the work arounds suggested in https://users.rust-lang.org/t/deriving-external-traits-on-external-structs/18198 to be able to integrate fancy-regex types with downstream/external types.
cc @ingalls
> Add new token type enum, make public struct more accessible

- src/lib.rs
Making some changes to the `TokenType` enum to support downstream functionality in https://github.com/ingalls/pt2itp/pull/468. Will keep this branch open until that PR is ready to merge.
cc @ingalls @samely
> Add serialize, deserialize traits to TokenType

- tokens/en.json
The `road` token in `en` should be categorized as a `way` type.
cc @mapbox/search
> Adds 'way' type to road token

- tokens/en.json
We forgot to categorize `Place` as a `way` type in our abbreviations.
cc @miccolis @ingalls @samely @mattciferri
> Make 'Place' a 'way' type

- tokens/en.json
We initially added the `farm/fm` as a stopgap because we didn't support cardinality changing tokens. 
We support cardinality changing tokens now and should update these tokens to their original intent
Documentation: https://en.wikipedia.org/wiki/Farm-to-market_road
Ref: https://github.com/mapbox/geocoder-feedback/issues/3005
Customer Pain: https://docs.google.com/spreadsheets/d/1tvVu-mDaeDWaQOIVujuzZxd4oNSgU7FmRK7904xjirI/edit#gid=0
> Farm-To-Market & Ranch-To-Market

- README.md
- test/test.js
- tokens/en.json
As a part of being able to handle missing ordinals in queries, this PR adds token replacement for  dropping ordinals while indexing. It adds a new property `reduceRelevance` which implies that we only perform the token replacement during index time and reduce the relevance and doesn't apply the token replacement during query time. 
cc @mapbox/search
> Handle missing ordinals

- test/fixtures/de-advanced.json
- test/fixtures/de-simple.json
- tokens/de.json
This PR removes unneeded German tokens. We were able to implement the regex of the current " str" replacement. Using the current str replacement of splitting "strasse", "straße" or "str" off into its own word also removed the need to add tokens such as "banhofstrasse".
> Remove unnecessary German tokens

- Cargo.toml
- src/lib.rs
rust-embed falls back to reading from the file system in debug builds,
which allowed a bad path to be used to access embedded token files in
our tests. This fixes the path used to access the embedded token files
and enables the debug-embed feature to force rust-embed to always embed
the token files.
/cc @mapbox/search
> Fix TokenFileImportNotSupported in release builds

- .circleci/config.yml
- src/lib.rs
This cleans up the existing clippy lint warnings and configures the CI build to fail if any warnings are introduced.
/cc @mapbox/search
> Enable clippy lint checks

- tokens/cs.json
The `"sev" => "s"` token replacement in Czech does weird things when combined with tokens from other languages in multi-language indexes, and doesn't seem obviously relevant other than to addresses, so this PR restricts it to only being used in addresses.
> Restrict 'sev' token replacement to addresses only

- tokens/fr.json
This PR adds a complex token replacement for cases where in France, we've seen users replace apostrophe's with a space for  articles/prepositions. Currently, we're only planning to apply this token replacement to addresses in France - given that we're most likely to see this behaviour there.
> Elision support

- tokens/fr.json
- Use French words for numbers and a few instances of plurals being used in rural areas of France.
- Properly set `spanBoundaries` parameter for multi-word tokens to be properly evaluated and matchied during linking.
> French number token updates

- tokens/pl.json
Obeserve some additional tokens can be added in to improve the matching between address street name and road network name in Poland. This helps solve ~700 address orphan clusters in Poland.
@ilissablech
> Add Poland Token

- CHANGELOG.md
- package.json
Bump version to 4.6.1 to add tokens for OSM new countriess: Slovak(SK), Slovania(SI), Serbia(RS), Lithuania(LT), Hungary(HU).
> bump version to 4.6.1

- CHANGELOG.md
- package.json
- tokens/hu.json
- tokens/ro.json
This PR is to update tokens in Hungary and Romania to improve the search accuracy. Bump the version to 4.6.2.
> Update hungary and romania tokens

- CHANGELOG.md
- package.json
- tokens/en.json
- tokens/fr.json
We added in elison support for France to support when people search by replacing apostrophes with a space for articles/prepositions. It's likely that similar search methods would be used in the French speaking parts of Canada.
cc: @mapbox/search-addresses
> Elison support for Canada

- CHANGELOG.md
- package.json
- tokens/lv.json
Add tokens for Latvia. Source: [libpostal](https://github.com/openvenues/libpostal/tree/master/resources/dictionaries/lv)
> Add latvian token

- CHANGELOG.md
- package.json
- tokens/lv.json
- tokens/sv.json
Continue Ilissa's work to fix the token regex. The `${1}` works differently in Rust and js, so that if we use [`${1}g`, `(.+)gatan$`], carmen will replace "Smalandsgatan" -> "${1}g", rather than "Smalandsgatan" -> "Smalandsg". New token use [`$1`, `(.+g)(?:atan)$`] instead.
> Sweden Token Updates

- tokens/lv.json
- tokens/sv.json
In Sweden we were getting unexpected network to address matches.
- Eyragatan was matching to a nearby Rudbecksgatan
- We had a regex of full: `(.+)gata` | canonical: `$1g`. What that would do for these two names is strip out the `Eyragata` and `Rudbecksgata`, leaving just `n` which is considered a cardinal for north. 
- With these changes we will make sure the regex goes to the end of the line (so that the full word will match `(.+)gatan$` and the replacement will look up the correct capture group so that the intended letter is kept (originally `$1g` would look up the capture group named 1g and not the capture group at index 1.
> Update Swedish regexes

- CHANGELOG.md
- package.json
- tokens/es.json
- tokens/fr.json
Spanish and French number tokens were initially added for processing purposes only, and haven't been thoroughly tested for indexing/querying. This PR applies the `onlyUseWhile` tag to each to them to limit their scope.
@mapbox/search-addresses
> Only use number abbreviations during processing

- CHANGELOG.md
- package.json
- tokens/en.json
- tokens/fr.json
Update postcode regex for Canada for both the English and French language.
cc @mapbox/search-addresses
> Canada postcode regex
